name: Run Script on PR Merge to Master

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run script.sh
        run: bash ./script.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.merge_commit_sha }}
        env:
          API_KEY: ${{ secrets.NR_API_KEY }}
